### ISSUE TITLE
Compiling on Intel MacOs

### ISSUE THREAD

**Issue by konpatsourakis** [andersforsgren/synja#2]
Hello, 
have you managed to compile on a MacOS ? Also do I need a specific version of rust compiler ? 
I can try and provide some errors but they are different depending on the version I am using 

Thanks!

**Comment by andersforsgren** [comment]
Hello, I have not tried compiling on OS X (mainly because I don’t have a mac)

I’m happy to take a look at your errors but it might be slow trying to fix it from my end unless I get my hands on mac!). I do want to fix a Mac release though.

**Comment by konpatsourakis** [comment]
Thank you,
when I am trying to compile with stable rustc 1.68.2
I am getting this:

```
$ synja % cargo nih-plug bundle synja --release                                         
   Compiling egui_extras_xt v0.1.0 (https://github.com/andersforsgren/egui_extras_xt?rev=aa4fd91941419393e5648389958caa4bbaca0eb1#aa4fd919)
error[E0554]: `#![feature]` may not be used on the stable release channel
 --> /Volumes/metalaksis/kpatch/.cargo/git/checkouts/egui_extras_xt-3adeaa7faa87f861/aa4fd91/egui_extras_xt/src/lib.rs:1:12
  |
1 | #![feature(step_trait)]
  |            ^^^^^^^^^^

For more information about this error, try `rustc --explain E0554`.
error: could not compile `egui_extras_xt` due to previous error
Error: Could not build synja

```

So I change to nightly 1.70.0

I run the commands again and I am getting this 

```
$ cargo nih-plug bundle synja --release 

Compiling synja v0.1.0 (/Volumes/metalaksis/kpatch/src/synja)
error[E0658]: use of unstable library feature 'lazy_cell'
 --> src/midi.rs:2:5
  |
2 | use std::sync::LazyLock;
  |     ^^^^^^^^^^^^^^^^^^^
  |
  = note: see issue #109736 <https://github.com/rust-lang/rust/issues/109736> for more information
  = help: add `#![feature(lazy_cell)]` to the crate attributes to enable

error[E0658]: use of unstable library feature 'lazy_cell'
  --> src/midi.rs:10:15
   |
10 | static PITCH: LazyLock<[f32; PITCH_TABLE_SIZE]> = LazyLock::new(|| {
   |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: see issue #109736 <https://github.com/rust-lang/rust/issues/109736> for more information
   = help: add `#![feature(lazy_cell)]` to the crate attributes to enable

error[E0658]: use of unstable library feature 'lazy_cell'
  --> src/midi.rs:10:51
   |
10 | static PITCH: LazyLock<[f32; PITCH_TABLE_SIZE]> = LazyLock::new(|| {
   |                                                   ^^^^^^^^
   |
   = note: see issue #109736 <https://github.com/rust-lang/rust/issues/109736> for more information
   = help: add `#![feature(lazy_cell)]` to the crate attributes to enable

error[E0658]: use of unstable library feature 'lazy_cell'
  --> src/midi.rs:19:14
   |
19 | static POW2: LazyLock<[f32; POW2_TABLE_SIZE]> = LazyLock::new(|| {
   |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: see issue #109736 <https://github.com/rust-lang/rust/issues/109736> for more information
   = help: add `#![feature(lazy_cell)]` to the crate attributes to enable

error[E0658]: use of unstable library feature 'lazy_cell'
  --> src/midi.rs:19:49
   |
19 | static POW2: LazyLock<[f32; POW2_TABLE_SIZE]> = LazyLock::new(|| {
   |                                                 ^^^^^^^^
   |
   = note: see issue #109736 <https://github.com/rust-lang/rust/issues/109736> for more information
   = help: add `#![feature(lazy_cell)]` to the crate attributes to enable

warning: the feature `once_cell` has been stable since 1.70.0-nightly and no longer requires an attribute to enable
 --> src/lib.rs:1:12
  |
1 | #![feature(once_cell)]
  |            ^^^^^^^^^
  |
  = note: `#[warn(stable_features)]` on by default

error[E0658]: use of unstable library feature 'lazy_cell'
  --> src/midi.rs:10:51
   |
10 | static PITCH: LazyLock<[f32; PITCH_TABLE_SIZE]> = LazyLock::new(|| {
   |                                                   ^^^^^^^^^^^^^
   |
   = note: see issue #109736 <https://github.com/rust-lang/rust/issues/109736> for more information
   = help: add `#![feature(lazy_cell)]` to the crate attributes to enable

error[E0658]: use of unstable library feature 'lazy_cell'
  --> src/midi.rs:19:49
   |
19 | static POW2: LazyLock<[f32; POW2_TABLE_SIZE]> = LazyLock::new(|| {
   |                                                 ^^^^^^^^^^^^^
   |
   = note: see issue #109736 <https://github.com/rust-lang/rust/issues/109736> for more information
   = help: add `#![feature(lazy_cell)]` to the crate attributes to enable

For more information about this error, try `rustc --explain E0658`.
warning: `synja` (lib) generated 1 warning
error: could not compile `synja` (lib) due to 7 previous errors; 1 warning emitted
Error: Could not build synja

```

If you need something else please let me know! 
I have very limited experience with rust so it might be something obvious

**Comment by andersforsgren** [comment]
A bit unsure what’s going on, maybe the feature has been renamed from once_cell to lazy_cell or something.

try adding 

#![feature(lazy_cell)]

to the top of lib.rs and compile again
